name: Build HF PR Documentation

on:
  pull_request:
    paths:
      - "docs/**"
      - "examples/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: pollen-robotics/doc-builder/.github/workflows/build_pr_documentation.yml@add-python-version-input
    with:
      repo_owner: pollen-robotics
      commit_sha: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ github.event.number }}
      package: reachy_mini
      python_version: "3.11"
