name: Build HF documentation

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g. v1.4.0) - Leave empty for standard main build"
        required: false
        type: string

  release:
    types:
      - published

  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "examples/**"

jobs:
  build:
    uses: pollen-robotics/doc-builder/.github/workflows/build_main_documentation.yml@add-python-version-input
    with:
      repo_owner: pollen-robotics
      commit_sha: ${{ github.sha }}
      package: reachy_mini
      python_version: "3.11"
      additional_args: >-
        ${{
          (github.event_name == 'release' && format('--version {0}', github.event.release.tag_name)) ||
          (inputs.version != '' && format('--version {0}', inputs.version)) ||
          ''
        }}
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
